[2024-08-08T09:33:37.370+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T09:33:37.405+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:31:32.337668+00:00 [queued]>
[2024-08-08T09:33:37.412+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:31:32.337668+00:00 [queued]>
[2024-08-08T09:33:37.412+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-08T09:33:37.501+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): limpieza> on 2024-08-08 09:31:32.337668+00:00
[2024-08-08T09:33:37.512+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'limpieza', 'manual__2024-08-08T09:31:32.337668+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmpe9pcb65s']
[2024-08-08T09:33:37.512+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-08T09:33:37.513+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask limpieza
[2024-08-08T09:33:37.514+0000] {standard_task_runner.py:64} INFO - Started process 220 to run task
[2024-08-08T09:33:37.578+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T09:31:32.337668+00:00 [running]> on host 9fb498cdebb0
[2024-08-08T09:33:37.650+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='limpieza' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T09:31:32.337668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-08T09:31:32.337668+00:00'
[2024-08-08T09:33:37.651+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T09:33:41.675+0000] {warnings.py:112} WARNING - /opt/***/dags/dag_prueba_tecnica.py:41: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient='records')

[2024-08-08T09:33:54.969+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-08-08T09:35:11.714+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T09:35:11.714+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customers, 2200) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_prueba_tecnica.py", line 63, in limpiezaDatos
    df_normado.to_sql('customers', pg_hook.get_sqlalchemy_engine(), if_exists='replace')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1948, in to_sql
    table = self.prep_table(
            ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1852, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 936, in create
    self._execute_create()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 922, in _execute_create
    self.table.create(bind=self.pd_sql.con)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
    self.connection.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customers, 2200) already exists.

[SQL: 
CREATE TABLE customers (
	index BIGINT, 
	"rev_Mean" FLOAT(53), 
	"mou_Mean" FLOAT(53), 
	"totmrc_Mean" FLOAT(53), 
	"da_Mean" FLOAT(53), 
	"ovrmou_Mean" FLOAT(53), 
	"ovrrev_Mean" FLOAT(53), 
	"vceovr_Mean" FLOAT(53), 
	"datovr_Mean" FLOAT(53), 
	"roam_Mean" FLOAT(53), 
	change_mou FLOAT(53), 
	change_rev FLOAT(53), 
	"drop_vce_Mean" FLOAT(53), 
	"drop_dat_Mean" FLOAT(53), 
	"blck_vce_Mean" FLOAT(53), 
	"blck_dat_Mean" FLOAT(53), 
	"unan_vce_Mean" FLOAT(53), 
	"unan_dat_Mean" FLOAT(53), 
	"plcd_vce_Mean" FLOAT(53), 
	"plcd_dat_Mean" FLOAT(53), 
	"recv_vce_Mean" FLOAT(53), 
	"recv_sms_Mean" FLOAT(53), 
	"comp_vce_Mean" FLOAT(53), 
	"comp_dat_Mean" FLOAT(53), 
	"custcare_Mean" FLOAT(53), 
	"ccrndmou_Mean" FLOAT(53), 
	"cc_mou_Mean" FLOAT(53), 
	"inonemin_Mean" FLOAT(53), 
	"threeway_Mean" FLOAT(53), 
	"mou_cvce_Mean" FLOAT(53), 
	"mou_cdat_Mean" FLOAT(53), 
	"mou_rvce_Mean" FLOAT(53), 
	"owylis_vce_Mean" FLOAT(53), 
	"mouowylisv_Mean" FLOAT(53), 
	"iwylis_vce_Mean" FLOAT(53), 
	"mouiwylisv_Mean" FLOAT(53), 
	"peak_vce_Mean" FLOAT(53), 
	"peak_dat_Mean" FLOAT(53), 
	"mou_peav_Mean" FLOAT(53), 
	"mou_pead_Mean" FLOAT(53), 
	"opk_vce_Mean" FLOAT(53), 
	"opk_dat_Mean" FLOAT(53), 
	"mou_opkv_Mean" FLOAT(53), 
	"mou_opkd_Mean" FLOAT(53), 
	"drop_blk_Mean" FLOAT(53), 
	"attempt_Mean" FLOAT(53), 
	"complete_Mean" FLOAT(53), 
	"callfwdv_Mean" FLOAT(53), 
	"callwait_Mean" FLOAT(53), 
	churn FLOAT(53), 
	months FLOAT(53), 
	uniqsubs FLOAT(53), 
	actvsubs FLOAT(53), 
	new_cell FLOAT(53), 
	crclscod FLOAT(53), 
	asl_flag FLOAT(53), 
	totcalls FLOAT(53), 
	totmou FLOAT(53), 
	totrev FLOAT(53), 
	adjrev FLOAT(53), 
	adjmou FLOAT(53), 
	adjqty FLOAT(53), 
	avgrev FLOAT(53), 
	avgmou FLOAT(53), 
	avgqty FLOAT(53), 
	avg3mou FLOAT(53), 
	avg3qty FLOAT(53), 
	avg3rev FLOAT(53), 
	avg6mou FLOAT(53), 
	avg6qty FLOAT(53), 
	avg6rev FLOAT(53), 
	prizm_social_one FLOAT(53), 
	area FLOAT(53), 
	dualband FLOAT(53), 
	refurb_new FLOAT(53), 
	hnd_price FLOAT(53), 
	phones FLOAT(53), 
	models FLOAT(53), 
	hnd_webcap FLOAT(53), 
	truck FLOAT(53), 
	rv FLOAT(53), 
	ownrent FLOAT(53), 
	lor FLOAT(53), 
	dwlltype FLOAT(53), 
	marital FLOAT(53), 
	adults FLOAT(53), 
	infobase FLOAT(53), 
	income FLOAT(53), 
	numbcars FLOAT(53), 
	"HHstatin" FLOAT(53), 
	dwllsize FLOAT(53), 
	forgntvl FLOAT(53), 
	ethnic FLOAT(53), 
	kid0_2 FLOAT(53), 
	kid3_5 FLOAT(53), 
	kid6_10 FLOAT(53), 
	kid11_15 FLOAT(53), 
	kid16_17 FLOAT(53), 
	creditcd FLOAT(53), 
	eqpdays FLOAT(53), 
	"isParent" FLOAT(53)
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-08-08T09:35:12.039+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_prueba_tecnica, task_id=limpieza, run_id=manual__2024-08-08T09:31:32.337668+00:00, execution_date=20240808T093132, start_date=20240808T093337, end_date=20240808T093512
[2024-08-08T09:35:12.136+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task limpieza ((psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(customers, 2200) already exists.

[SQL: 
CREATE TABLE customers (
	index BIGINT, 
	"rev_Mean" FLOAT(53), 
	"mou_Mean" FLOAT(53), 
	"totmrc_Mean" FLOAT(53), 
	"da_Mean" FLOAT(53), 
	"ovrmou_Mean" FLOAT(53), 
	"ovrrev_Mean" FLOAT(53), 
	"vceovr_Mean" FLOAT(53), 
	"datovr_Mean" FLOAT(53), 
	"roam_Mean" FLOAT(53), 
	change_mou FLOAT(53), 
	change_rev FLOAT(53), 
	"drop_vce_Mean" FLOAT(53), 
	"drop_dat_Mean" FLOAT(53), 
	"blck_vce_Mean" FLOAT(53), 
	"blck_dat_Mean" FLOAT(53), 
	"unan_vce_Mean" FLOAT(53), 
	"unan_dat_Mean" FLOAT(53), 
	"plcd_vce_Mean" FLOAT(53), 
	"plcd_dat_Mean" FLOAT(53), 
	"recv_vce_Mean" FLOAT(53), 
	"recv_sms_Mean" FLOAT(53), 
	"comp_vce_Mean" FLOAT(53), 
	"comp_dat_Mean" FLOAT(53), 
	"custcare_Mean" FLOAT(53), 
	"ccrndmou_Mean" FLOAT(53), 
	"cc_mou_Mean" FLOAT(53), 
	"inonemin_Mean" FLOAT(53), 
	"threeway_Mean" FLOAT(53), 
	"mou_cvce_Mean" FLOAT(53), 
	"mou_cdat_Mean" FLOAT(53), 
	"mou_rvce_Mean" FLOAT(53), 
	"owylis_vce_Mean" FLOAT(53), 
	"mouowylisv_Mean" FLOAT(53), 
	"iwylis_vce_Mean" FLOAT(53), 
	"mouiwylisv_Mean" FLOAT(53), 
	"peak_vce_Mean" FLOAT(53), 
	"peak_dat_Mean" FLOAT(53), 
	"mou_peav_Mean" FLOAT(53), 
	"mou_pead_Mean" FLOAT(53), 
	"opk_vce_Mean" FLOAT(53), 
	"opk_dat_Mean" FLOAT(53), 
	"mou_opkv_Mean" FLOAT(53), 
	"mou_opkd_Mean" FLOAT(53), 
	"drop_blk_Mean" FLOAT(53), 
	"attempt_Mean" FLOAT(53), 
	"complete_Mean" FLOAT(53), 
	"callfwdv_Mean" FLOAT(53), 
	"callwait_Mean" FLOAT(53), 
	churn FLOAT(53), 
	months FLOAT(53), 
	uniqsubs FLOAT(53), 
	actvsubs FLOAT(53), 
	new_cell FLOAT(53), 
	crclscod FLOAT(53), 
	asl_flag FLOAT(53), 
	totcalls FLOAT(53), 
	totmou FLOAT(53), 
	totrev FLOAT(53), 
	adjrev FLOAT(53), 
	adjmou FLOAT(53), 
	adjqty FLOAT(53), 
	avgrev FLOAT(53), 
	avgmou FLOAT(53), 
	avgqty FLOAT(53), 
	avg3mou FLOAT(53), 
	avg3qty FLOAT(53), 
	avg3rev FLOAT(53), 
	avg6mou FLOAT(53), 
	avg6qty FLOAT(53), 
	avg6rev FLOAT(53), 
	prizm_social_one FLOAT(53), 
	area FLOAT(53), 
	dualband FLOAT(53), 
	refurb_new FLOAT(53), 
	hnd_price FLOAT(53), 
	phones FLOAT(53), 
	models FLOAT(53), 
	hnd_webcap FLOAT(53), 
	truck FLOAT(53), 
	rv FLOAT(53), 
	ownrent FLOAT(53), 
	lor FLOAT(53), 
	dwlltype FLOAT(53), 
	marital FLOAT(53), 
	adults FLOAT(53), 
	infobase FLOAT(53), 
	income FLOAT(53), 
	numbcars FLOAT(53), 
	"HHstatin" FLOAT(53), 
	dwllsize FLOAT(53), 
	forgntvl FLOAT(53), 
	ethnic FLOAT(53), 
	kid0_2 FLOAT(53), 
	kid3_5 FLOAT(53), 
	kid6_10 FLOAT(53), 
	kid11_15 FLOAT(53), 
	kid16_17 FLOAT(53), 
	creditcd FLOAT(53), 
	eqpdays FLOAT(53), 
	"isParent" FLOAT(53)
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 220)
[2024-08-08T09:35:12.294+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-08T09:35:12.308+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-08T09:35:12.318+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
