[2024-08-07T15:46:53.674+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:46:53.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza scheduled__2024-07-28T00:00:00+00:00 [queued]>
[2024-08-07T15:46:53.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza scheduled__2024-07-28T00:00:00+00:00 [queued]>
[2024-08-07T15:46:53.707+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 6
[2024-08-07T15:46:53.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): limpieza> on 2024-07-28 00:00:00+00:00
[2024-08-07T15:46:53.728+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'limpieza', 'scheduled__2024-07-28T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmpx3hsqarz']
[2024-08-07T15:46:53.727+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=195) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T15:46:53.729+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask limpieza
[2024-08-07T15:46:53.729+0000] {standard_task_runner.py:64} INFO - Started process 221 to run task
[2024-08-07T15:46:53.769+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.limpieza scheduled__2024-07-28T00:00:00+00:00 [running]> on host 278ba5711b2c
[2024-08-07T15:46:53.846+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='limpieza' AIRFLOW_CTX_EXECUTION_DATE='2024-07-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-28T00:00:00+00:00'
[2024-08-07T15:46:53.847+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:47:08.007+0000] {warnings.py:112} WARNING - /opt/***/dags/dag_prueba_tecnica.py:37: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient='records')

[2024-08-07T15:47:22.676+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-08-07T15:48:23.832+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-07T15:48:23.833+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:48:23.841+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_prueba_tecnica, task_id=limpieza, run_id=scheduled__2024-07-28T00:00:00+00:00, execution_date=20240728T000000, start_date=20240807T154653, end_date=20240807T154823
[2024-08-07T15:48:24.009+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-07T15:48:24.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
