[2024-08-08T14:18:56.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-08T14:18:56.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T14:18:40.018038+00:00 [queued]>
[2024-08-08T14:18:56.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T14:18:40.018038+00:00 [queued]>
[2024-08-08T14:18:56.286+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-08T14:18:56.298+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): limpieza> on 2024-08-08 14:18:40.018038+00:00
[2024-08-08T14:18:56.318+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'limpieza', 'manual__2024-08-08T14:18:40.018038+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmp_cxv9o_t']
[2024-08-08T14:18:56.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-08T14:18:56.319+0000] {standard_task_runner.py:91} INFO - Job 217: Subtask limpieza
[2024-08-08T14:18:56.320+0000] {standard_task_runner.py:64} INFO - Started process 101 to run task
[2024-08-08T14:18:56.356+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.limpieza manual__2024-08-08T14:18:40.018038+00:00 [running]> on host bce4ad349ea9
[2024-08-08T14:18:56.421+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='limpieza' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T14:18:40.018038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-08T14:18:40.018038+00:00'
[2024-08-08T14:18:56.422+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-08T14:18:59.181+0000] {warnings.py:112} WARNING - /opt/***/dags/dag_prueba_tecnica.py:40: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient='records')

[2024-08-08T14:19:08.520+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-08-08T14:19:43.277+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-08T14:19:43.278+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-08T14:19:43.285+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_prueba_tecnica, task_id=limpieza, run_id=manual__2024-08-08T14:18:40.018038+00:00, execution_date=20240808T141840, start_date=20240808T141856, end_date=20240808T141943
[2024-08-08T14:19:43.439+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-08T14:19:43.456+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-08T14:19:43.459+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
